### ISSUE TITLE
Общедоступный банк маршрутов

### ISSUE THREAD

**Issue by Octochick** [muerwre/orchidMap#10]
Возможность просматривать сохранённые маршруты всех, кто рисует в редакторе и сделал свой маршрут публичным. Прикрутить опцию публичный/приватный. Соответственно, нужны аккаунты или единый банк маршрутов (на мой взгляд, это более интересный вариант), в который будут сливаться все с меткой "публичный".  Это ж капец. Вторая страва или как? Не знаю, насколько это сложно реализовать. 
Кто не знает куда ехать, просто выбирает любой понравившийся в коллекторе и едет.

**Comment by muerwre** [comment]
Добавлю переключатель "Виден всем" при сохранении

**Comment by muerwre** [comment]
(Реализовано)
