### ISSUE TITLE
Distance points

### ISSUE THREAD

**Issue by Octochick** [muerwre/orchidMap#16]
Кроме конечной точки с колометражом необходимы поинты с километрами на треке через каждые 10 км на коротких и каждые 20-30 на длинных маршрутах (больше 100км). Для понимания, где можно сойти и для примерного расчёта своих сил.

**Comment by muerwre** [comment]
![Screen Shot 2019-08-09 at 10 43 21 AM](https://user-images.githubusercontent.com/33246675/62752645-920fa080-ba92-11e9-9f3f-6613b419e6f2.png)
Уже реализовано.
